version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT

    environment:
      - DB_HOST=db
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT_CONTAINER
    stdin_open: true
    tty: true

    networks:
      - mynetwork
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.0.27
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports:
      - $DB_PORT_LOCAL:$DB_PORT_CONTAINER
    networks:
      - mynetwork

volumes:
  db:
